"""Export the request chain as manually-tracked event items.

Requests are a linear chain: each one's region is itself, and the next one's
entrance rule requires it. When requestsanity is off they are not checks at
all, so nothing tells the tracker which ones are done -- and the chain gates 64
locations. Even with requestsanity on, "have you done request N" is only
inferred from holding the ingredients its entrance rule names, which is an
approximation of actually having handed it in.

So each request gets a toggle the player flips when they complete it, the way
the Pokemon FRLG tracker handles its events, and the logic treats a request
region as reached when its toggle is on.

Writes:
    items/events.json                 one toggle per request
    scripts/logic/request_events.lua  request region name -> item code
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PACK = os.path.dirname(os.path.dirname(HERE)) + '/'
sys.path.insert(0, HERE)
from load import apworld                            # noqa: E402

AP = apworld()
L = AP.Locations

# The pack's own request-board icon, shared by all 93 until per-request art
# can be pulled from the game data (see tools/README.md).
ICON = "images/settings/opt_requestsanity.png"


def code_for(name):
    """A stable item code from a request title."""
    slug = re.sub(r'[^a-z0-9]+', '', name.lower())
    return 'req_' + slug


def main():
    reqs = [(d.name, d.apid) for name, d in L.request_data_table.items()
            if d.include]
    # chain order: the apworld builds the table in the order a player meets them
    out = PACK + 'items/events.json'

    seen, items, mapping = set(), [], []
    for name, apid in reqs:
        code = code_for(name)
        if code in seen:
            raise SystemExit("two requests slug to %r: %s" % (code, name))
        seen.add(code)
        # export_item_tiles.py writes the game's own picture for a request to
        # images/events/<code>.png, slugging the name exactly as code_for does.
        # So ask the disk, rather than reading back the events.json this run is
        # about to replace -- which silently loses all 93 if that file is gone.
        art = 'images/events/%s.png' % code
        img = art if os.path.exists(PACK + art) else ICON
        items.append({
            "name": name,
            "type": "toggle",
            "img": img,
            "disabled_img": img,
            "disabled_img_mods": "@disabled",
            "initial_active_state": False,
            "codes": code,
        })
        mapping.append((name, code))

    with open(out, 'w', encoding='utf-8', newline='\n') as f:
        json.dump(items, f, indent=4, ensure_ascii=False)
        f.write("\n")
    print("wrote %s  (%d request toggles)" % (out, len(items)))

    out2 = PACK + 'scripts/logic/request_events.lua'
    with open(out2, 'w', encoding='utf-8', newline='\n') as f:
        f.write("-- GENERATED by tools/apworld/export_requests.py\n")
        f.write("-- Request region name -> the toggle that marks it done.\n")
        f.write("-- Each request is its own region in the apworld's graph, so\n")
        f.write("-- marking one done makes that region reachable and opens the\n")
        f.write("-- next link in the chain.\n")
        f.write("RF4_REQUEST_EVENT = {\n")
        for name, code in mapping:
            f.write('    ["%s"] = "%s",\n' % (name.replace('"', '\\"'), code))
        f.write("}\n")
    print("wrote %s" % out2)

    # The grid, in chain order, sized to fill the box the panel reserves for it
    # (layouts/item_panel*.json): 408x748 vertical, 1020x306 horizontal.
    #
    #   vertical    9 x 44px cells = 396 of ~398 usable, 11 rows = 484 of 748
    #   horizontal 21 x 48px cells = 1008 of ~1010 usable, 5 rows = 240 of 306
    MARGIN = 2

    def build(width, icon):
        rows, row = [], []
        for _, code in mapping:
            row.append(code)
            if len(row) == width:
                rows.append(row); row = []
        if row:
            rows.append(row)
        return {
            "type": "array",
            "orientation": "vertical",
            "margin": "0,0",
            "content": [{
                "type": "itemgrid",
                "item_margin": "%d,%d" % (MARGIN, MARGIN),
                "h_alignment": "center",
                "item_size": "%d,%d" % (icon, icon),
                "rows": rows,
            }],
        }

    grid = {"event_grid": build(9, 40), "event_grid_horizontal": build(21, 44)}
    out3 = PACK + 'layouts/events.json'
    with open(out3, 'w', encoding='utf-8', newline='\n') as f:
        json.dump(grid, f, indent=4, ensure_ascii=False)
        f.write("\n")
    print("wrote %s  (%d rows of 9 at 40px / %d rows of 21 at 44px)"
          % (out3, len(grid["event_grid"]["content"][0]["rows"]),
             len(grid["event_grid_horizontal"]["content"][0]["rows"])))


if __name__ == '__main__':
    main()
