"""Export AP location id -> the pack option that gates it, and the barrier/box
room metadata the new pins need.

The apworld tags every location with a loc_type ("chest", "barrier", "box",
"request", ...) in Locations.py, which is the source for which sanity option
controls a check.

Writes:
    scripts/autotracking/option_for_location.lua   id -> "opt_*sanity"
    scripts/autotracking/barrier_meta.lua          id -> {region, room, kind}
    tools/generated/location_kinds.json            id -> loc_type

The third is for the tools rather than the pack: it says what every check IS --
shipment, tame, friendship, chest, barrier, box, search -- so nothing downstream
has to infer a kind from the wording of a node name.

The second is what lets the barrier, box and search checks be grouped per region
and per room without re-reading the game's flag json at runtime.
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PACK = os.path.dirname(os.path.dirname(HERE)) + '/'
sys.path.insert(0, HERE)
import load
from load import apworld, lua_str                   # noqa: E402

AP = apworld()
L = AP.Locations

# loc_type -> the pack's option code. A type with no option is always on.
OPTION_FOR_TYPE = {
    'chest':      'opt_chestsanity',
    'request':    'opt_requestsanity',
    'friendship': 'opt_friendsanity',
    'tame':       'opt_tamesanity',
    'outfit':     'opt_outfitsanity',
    'barrier':    'opt_barriersanity',
    'box':        'opt_boxsanity',
    'search':     'opt_searchsanity',
}
# The types that are an object in a room, discovered rather than listed. A kind
# the apworld adds is picked up here on its own; its toggle still has to be named
# above, since the pack has to have one for the player to switch.
MAP_OBJECT = load.map_kinds(AP)


def main():
    by_id = {}
    for name, d in L.location_data_table.items():
        if d.address is None:
            continue
        opt = OPTION_FOR_TYPE.get(d.loc_type)
        if opt:
            by_id[d.address] = opt

    # A shipment's option follows what is being shipped, which loc_type cannot
    # express, so those ids are carried over from the table already on disk.
    # That cannot self-correct, so anything it gets wrong is pinned here.
    FIX = {
        # upstream split one collided "Gloves" row into these two
        1850916: 'opt_forgesanity',    # Forge Shipment - Gloves (Weapon)
        1851018: 'opt_craftsanity',    # Crafting Shipment - Gloves (Accessory)
    }

    # carry those shipment ids over from the table already on disk
    out = PACK + 'scripts/autotracking/option_for_location.lua'
    kept = 0
    if os.path.exists(out):
        for m in re.finditer(r'\[(\d+)\]\s*=\s*"([a-z_]+)"',
                             open(out, encoding='utf-8').read()):
            i = int(m.group(1))
            if i not in by_id:
                by_id[i] = m.group(2)
                kept += 1

    by_id.update(FIX)
    codes = sorted(set(by_id.values()))

    with open(out, 'w', encoding='utf-8', newline='\n') as f:
        f.write("-- GENERATED by tools/apworld/export_location_options.py\n")
        f.write("-- AP location id -> the pack option that gates it, from the\n")
        f.write("-- apworld's own loc_type. Shipment ids keep the split the\n")
        f.write("-- hand-written table had, since loc_type cannot express it.\n")
        f.write("OPTION_FOR_LOCATION = {\n")
        for i in sorted(by_id):
            f.write("    [%d] = %s,\n" % (i, lua_str(by_id[i])))
        f.write("}\n")
        # Every option that actually gates a location. location_options.lua
        # iterates this to correct the toggles from the room, so a list kept by
        # hand there silently stops correcting whatever it is missing.
        f.write("\n-- every option that gates a location, for location_options.lua\n")
        f.write("OPTION_CODES = {\n")
        for code in codes:
            f.write("    %s,\n" % lua_str(code))
        f.write("}\n")
    print("wrote %s" % out)
    print("  ids gated        %5d" % len(by_id))
    print("  kept from before %5d  (shipment splits)" % kept)
    print("  options          %5d" % len(codes))

    # Room metadata for the object checks, restricted to ids that really are AP
    # locations: an entry in a flag table does not have to become one.
    real = {d.address for d in L.location_data_table.values()
            if d.loc_type in MAP_OBJECT and d.address is not None}
    rooms, dropped = {}, []
    for kind in MAP_OBJECT:
        for name, d in getattr(L, kind + '_data_table').items():
            # RF4MapObj, not RF4LocationData: the id lives on .apid and the
            # room number is already parsed out for us
            if d.apid is None:
                continue
            if d.apid not in real:
                dropped.append((d.apid, d.loc_name))
                continue
            rooms[d.apid] = (d.region, d.room_number, kind, d.loc_name)

    kinds = {str(d.address): d.loc_type
             for d in L.location_data_table.values() if d.address is not None}
    out3 = PACK + 'tools/generated/location_kinds.json'
    with open(out3, 'w', encoding='utf-8', newline='\n') as f:
        json.dump(kinds, f, indent=1, sort_keys=True)
        f.write('\n')
    print("wrote %s" % out3)
    print("  kinds            %5d  %s" % (
        len(kinds), ' '.join('%s %d' % (k, sum(1 for v in kinds.values() if v == k))
                             for k in sorted(set(kinds.values())))))

    out2 = PACK + 'scripts/autotracking/barrier_meta.lua'
    with open(out2, 'w', encoding='utf-8', newline='\n') as f:
        f.write("-- GENERATED by tools/apworld/export_location_options.py\n")
        f.write("-- barrier and box checks: id -> {region, room number, kind}\n")
        f.write("RF4_BARRIER_META = {\n")
        for i in sorted(rooms):
            region, room, kind, name = rooms[i]
            f.write("    [%d] = {%s, %d, %s},   -- %s\n"
                    % (i, lua_str(region), room, lua_str(kind), name))
        f.write("}\n")
    print("wrote %s" % out2)
    print("  map-object ids   %5d" % len(rooms))
    if dropped:
        print("  dropped          %5d  (in the flag tables, not AP locations)"
              % len(set(i for i, _ in dropped)))
        for i, n in sorted(set(dropped))[:12]:
            print("      %d  %s" % (i, n))


if __name__ == '__main__':
    main()
