"""Redraw the pack's map images from the game's own art.

Frame, art, room labels and caption are composed so that everything lands where
the capture being replaced had it -- the pins in `locations/*.json` are placed
in these images' coordinates, so the geometry is not ours to change.

    python3 tools/gamedata/render_maps.py [--out DIR] [map ...]

Two files configure it. `tools/map_art.json` is written by hand and says which
texture draws each image, how several are arranged, and the caption:

    "<image>": {
      "caption": ["Yokmir Cave", "Floor 2"],
      "art": [{"tex": "mini_map_07_dung_g_1", ...}]
    }

`tools/generated/map_layout.json` is `tools/gamedata/map_art.py`'s output and
says where each texture lands.

`x, y, w, h` are the destination rect of the texture's TRIMMED art in 670x600
canvas coordinates, from `tools/gamedata/map_art.py`.

Room labels come from `tools/generated/room_positions.json` -- `{map name: {code: [x, y]}}`
in these same coordinates, generated by `tools/gamedata/derive_rooms.py`. Which of them
are drawn is `show` in `rooms.json`; `"labels": false` in `map_art.json` turns
off a whole map, which the Overworld and Selphia use.
"""
import json
import os
import subprocess
import sys

from map_art import solid_box, texture_size         # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
# paths also pins SOURCE_DATE_EPOCH, so ImageMagick leaves the tIME chunk out
from paths import (ART, CONVERT, FONT, FRAME,       # noqa: E402
                   LABEL_FONT, PACK, need)
LABEL_SIZE = 11
LABEL_FILL, LABEL_HALO = '#2a1c07', '#f7eec9'
SHOWN = None
# With -gravity NorthWest, `-annotate +X+Y` puts the glyph box at (X, Y+3) and
# caps are 8px tall here, so centring on a room point is a fixed shift once the
# string's width is known.
LABEL_DY, LABEL_CAP = 3, 8
_WIDTH = {}


def label_width(text):
    if text not in _WIDTH:
        o = subprocess.run([CONVERT, '-font', LABEL_FONT, '-pointsize', str(LABEL_SIZE),
                            '-format', '%w', 'label:' + text, 'info:'],
                           capture_output=True, text=True).stdout
        _WIDTH[text] = int(o) - 2       # label: pads a pixel either side
    return _WIDTH[text]

W, H = 670, 600
FRAME_BOX = (0, 0, 482, 432)      # the panel inside the 512 square

# The panel body is 80% transparent in game, so it reads as whatever is behind
# it. Here it sits on the page, not on grass.
PAGE = '#fbf7e0'

# Upscaling the art softens it, because the alpha ramp that draws the outline
# widens with the image. Treat alpha as a distance field and re-level it.
RAMP = ('-channel', 'A', '-level', '46%,54%', '+channel')

CAP_FILL, CAP_SHADOW = '#f2f5f0', '#000000'
CAP_ONE = (32, 580)               # one line: size, baseline
CAP_TWO = ((32, 570), (22, 595))  # two lines


def run(args):
    r = subprocess.run(args, capture_output=True)
    if r.returncode:
        sys.exit(args[0] + ': ' + r.stderr.decode()[:400])


def frame(dst):
    x, y, w, h = FRAME_BOX
    run([CONVERT, FRAME, '-crop', '%dx%d+%d+%d' % (w, h, x, y), '+repage',
         '-filter', 'Lanczos', '-resize', '%dx%d!' % (W, H),
         '-background', PAGE, '-flatten', dst])


def compose(img, cfg, out, name):
    cmd = [CONVERT, out + '.frame.png']
    for piece in cfg['art']:
        # x/y/w/h is the box of the SOLID art. Draw the whole texture, so the
        # soft glow around a map survives, and shift it so the art lands there.
        art_w, _, art_x, art_y = solid_box(piece['tex'])
        scale = piece['w'] / art_w
        src = ART + piece['tex'] + '.png'
        # solid_box has already decoded this texture, so its full size is known
        full = texture_size(piece['tex'])
        cmd += ['(', src,
                '-filter', 'Lanczos',
                '-resize', '%dx%d!' % (round(full * scale), round(full * scale)),
                *RAMP, ')',
                '-geometry', '+%d+%d' % (round(piece['x'] - art_x * scale),
                                         round(piece['y'] - art_y * scale)),
                '-compose', 'over', '-composite']
    cmd += ['-font', LABEL_FONT, '-pointsize', str(LABEL_SIZE), '-gravity', 'NorthWest']
    # which labels are drawn is a field in rooms.json, not a naming rule: a room
    # known only by its map number is data, not a '#' prefix to test for
    rooms = {} if cfg.get('labels') is False else {
        k: v for k, v in cfg.get('rooms', {}).items()
        if SHOWN is None or k in SHOWN.get(name, ())}
    for code, (cx, cy) in sorted(rooms.items()):
        x = cx - label_width(code) // 2
        y = cy - LABEL_DY - LABEL_CAP // 2
        # halo first, then the glyph over it
        cmd += ['-stroke', LABEL_HALO, '-strokewidth', '3',
                '-fill', LABEL_HALO, '-annotate', '%+d%+d' % (x, y), code,
                '-stroke', 'none', '-fill', LABEL_FILL,
                '-annotate', '%+d%+d' % (x, y), code]
    cap = cfg.get('caption') or []
    if len(cap) == 1:
        cap = [(cap[0], *CAP_ONE)]
    elif len(cap) == 2:
        cap = [(cap[0], *CAP_TWO[0]), (cap[1], *CAP_TWO[1])]
    for text, size, base in cap:
        for fill, dx, dy in ((CAP_SHADOW, 0, 2), (CAP_FILL, 0, 0)):
            cmd += ['-font', FONT, '-pointsize', str(size), '-fill', fill,
                    '-gravity', 'North',
                    '-annotate', '+%d+%d' % (dx, base - size + dy), text]
    cmd += [out + '/' + img]
    run(cmd)


def main():
    wanted = sys.argv[1:]
    out = PACK + 'images/maps'
    if wanted and wanted[0] == '--out':
        out, wanted = wanted[1], wanted[2:]
    os.makedirs(out, exist_ok=True)
    global SHOWN
    # Which labels the maps draw is written out by derive_rooms, not asked of it:
    # this only ever reads generated files, so it runs whatever else has been
    # built yet. With no such file every label in room_positions.json is drawn.
    path = PACK + 'tools/generated/room_shown.json'
    SHOWN = ({m: set(v) for m, v in json.load(open(path)).items()}
             if os.path.exists(path) else None)
    cfg = json.load(open(os.environ.get(
        'MAP_LAYOUT', PACK + 'tools/generated/map_layout.json')))
    # the captions and the labels flag are written by hand, so they stay in
    # the input file rather than the one map_art.py rewrites
    for img, hand in json.load(open(PACK + 'tools/map_art.json')).items():
        for key in ('caption', 'labels'):
            if key in hand:
                cfg.setdefault(img, {})[key] = hand[key]
    rooms = json.load(open(os.environ.get('ROOM_POS', PACK + 'tools/generated/room_positions.json')))
    maps = {m['img'].replace('images/maps/', ''): m['name']
            for m in json.load(open(PACK + 'maps/maps.json'))}
    for img, name in maps.items():
        placed = rooms.get(name)
        if placed:
            cfg.setdefault(img, {}).setdefault('rooms', {}).update(placed)
    frame(out + '.frame.png')
    drawn = 0
    for img in sorted(cfg):
        if wanted and img not in wanted:
            continue
        compose(img, cfg[img], out, maps.get(img, img))
        drawn += 1
    os.remove(out + '.frame.png')
    print('rendered %d maps into %s' % (drawn, out))


if __name__ == '__main__':
    main()
