Tracker:AddLocations("locations/Anywhere (Rare).json")
Tracker:AddLocations("locations/Autumn Field.json")
Tracker:AddLocations("locations/Autumn River.json")
Tracker:AddLocations("locations/Autumn Road.json")
Tracker:AddLocations("locations/Autumn Spring.json")
Tracker:AddLocations("locations/Cluck Cluck Nest.json")
Tracker:AddLocations("locations/Cooking.json")
Tracker:AddLocations("locations/Crafting.json")
Tracker:AddLocations("locations/Delirium Lava Ruins.json")
Tracker:AddLocations("locations/Demons Den.json")
Tracker:AddLocations("locations/Field Dungeon.json")
Tracker:AddLocations("locations/Floating Empire.json")
Tracker:AddLocations("locations/Forge.json")
Tracker:AddLocations("locations/Idra Cave.json")
Tracker:AddLocations("locations/Leon Karnak.json")
Tracker:AddLocations("locations/Maya Road.json")
Tracker:AddLocations("locations/Obsidian Mansion.json")
Tracker:AddLocations("locations/Revival Cave.json")
Tracker:AddLocations("locations/Rune Prana.json")
Tracker:AddLocations("locations/Sechs Territory.json")
Tracker:AddLocations("locations/Selphia.json")
Tracker:AddLocations("locations/Selphia Plains.json")
Tracker:AddLocations("locations/Sercerezo Hill.json")
Tracker:AddLocations("locations/Sharance Maze.json")
Tracker:AddLocations("locations/Spring Spring.json")
Tracker:AddLocations("locations/Summer Spring.json")
Tracker:AddLocations("locations/Water Ruins.json")
Tracker:AddLocations("locations/Winter Spring.json")
Tracker:AddLocations("locations/Yokmir Forest.json")
Tracker:AddLocations("locations/Overworld.json")
